### PR TITLE
feat: 🎸 add options `enableHtmlImagesUploader`

### PR DESCRIPTION
**Pull request by shiyiya**

### CODE REVIEW

**Comment by Saul-Mirone** [comment]
Why do we need this flag?

If you're trying to solve the conflict between upload plugin and clipboard plugin, I've already done that by this commit:
https://github.com/Saul-Mirone/milkdown/commit/83632be0166724ab071ab81dc07ddab8cba186f4

**Comment by shiyiya** [comment]
**Copy an image from a chrome page to get the `html`.
You can choose to use the url of the copied image instead of uploading a copy

**Comment by Saul-Mirone** [comment]
I have a little concern about this, since upload plugin can handle things more than upload image, (for example, upload .md files), I think we should use a more generic way to do this.

IMO, we can expose a custom hook for users, such as `filterDrop: (event: DragEvent) => boolean`, return `true` when this drop event can be handled by this plugin. And we can also provide a `filterPaste` to do similar things. in paste event.

**Comment by shiyiya** [comment]
This may be a special case, you can copy images from a web page, but you can't do it to copy (copy rather than drag and drop) md or other files (I'm not sure, maybe a blob stream?) And it doesn't get `html`.

**Comment by Saul-Mirone** [comment]
But it seems that when you paste pictures from html the current milkdown will use the web url directly?

**Comment by shiyiya** [comment]
Set `enableHtmlImagesUploader` to true upload plugin will handle it.

**Comment by Saul-Mirone** [comment]
When copy image from html, the file list will be empty so the uploader won't work.
And prosemirror should handle this case by default.

4id4UXFwey

**Comment by shiyiya** [comment]
`backgroundimage`: filelist `false` html `true`
`<image/>`： filelist `true` html `true`

**Comment by shiyiya** [comment]
The upload plugin works in the following cases.
- when filelist is not empty and html is empty.
- when both filelist and html are not empty and enablehtmluploder is true.

**Comment by Saul-Mirone** [comment]
OK, I get it.

Could you please rename this flag into `enableHtmlUploader` and update the README.md file for this flag?

**Comment by Saul-Mirone** [comment]
What if pasted content has both images and other contents (such as heading and paragrpah)?

**Pull request merged**
