### PR TITLE
feat: Some common editor features

### PR DESCRIPTION
**Pull request by xiadd**
- [x] list tab/shift+tab key event
- [x] common hot keys
- [x] Tab indent

### CODE REVIEW

**Comment by xiadd** [comment]
@Saul-Mirone 
list tab/shift+tab key event conlict with tab-indent，I have no idea how to solve this problem，maybe should remove one of them

**Comment by Saul-Mirone** [comment]
> @Saul-Mirone
> list tab/shift+tab key event conlict with tab-indent，I have no idea how to solve this problem，maybe should remove one of them

Maybe we can use Mod+Space/Shift+Space for list?

**Comment by xiadd** [comment]
> > @Saul-Mirone
> > list tab/shift+tab key event conlict with tab-indent，I have no idea how to solve this problem，maybe should remove one of them
> 
> Maybe we can use Mod+Space/Shift+Space for list?

Shift+Space is better, Mod+Space is Macos spolight's hot key，I will try later

**Comment by xiadd** [comment]
@Saul-Mirone 

hello

Is `Mod-]`\`Mod-[` ok? I just found `Shift-Space` not working.

**Comment by Saul-Mirone** [comment]
> @Saul-Mirone
> 
> hello
> 
> Is `Mod-]`,`Mod-[` ok? I just found `Shift-Space` not working.

I think it's ok.

**Comment by xiadd** [comment]
@Saul-Mirone 
done

**Comment by Saul-Mirone** [comment]
> @Saul-Mirone
> done

Seems there's conflicts need to be resolved.

**Pull request closed without merging**
