### PR TITLE
feat: plugin loader

### PR DESCRIPTION
**Pull request by Saul-Mirone**
#11

### CODE REVIEW

**Comment by Saul-Mirone** [comment]
@xiadd
Please take a look at this, we will use this as our standard plugin spec.

**Comment by xiadd** [comment]
nice👍

I hava a problem, How to handle duplication with built-in nodes or marks? override？

**Comment by Saul-Mirone** [comment]
> nice👍
> 
> I hava a problem, How to handle duplication with built-in nodes or marks? override？

It seems that override is the best way, we can add some warning message if there are duplicate nodes.

**Comment by xiadd** [comment]
> > nice👍
> > I hava a problem, How to handle duplication with built-in nodes or marks? override？
> 
> It seems that override is the best way, we can add some warning message if there are duplicate nodes.

Can theme also be a plugin? now theme is actually css override

**Comment by Saul-Mirone** [comment]
> > > nice👍
> > > I hava a problem, How to handle duplication with built-in nodes or marks? override？
> > 
> > 
> > It seems that override is the best way, we can add some warning message if there are duplicate nodes.
> 
> Can theme also be a plugin? now theme is actually css override

Theme as a plugin, that's a good point.
How do you think we can design them?

**Comment by xiadd** [comment]
我们是否能秉承单一职责原则，一个插件干一件事，比如node作为一个插件而不是一个插件引入多个node，

a node as a plugin
a mark as a plugin
a prosemirror plugin as a plugin
a markdown plugin as a plugin
a theme as a plugin

这样后续扩展应该会方便很多

**Comment by Saul-Mirone** [comment]
> 我们是否能秉承单一职责原则，一个插件干一件事，比如node作为一个插件而不是一个插件引入多个node，
> 
> a node as a plugin
> a mark as a plugin
> a prosemirror plugin as a plugin
> a markdown plugin as a plugin
> a theme as a plugin
> 
> 这样后续扩展应该会方便很多

那可能一个feature需要的plugin很多，例如table这个feature，你会需要很多plugin，这样会不会太琐碎了。

**Comment by xiadd** [comment]
> 那可能一个feature需要的plugin很多，例如table这个feature，你会需要很多plugin，这样会不会太琐碎了。

plugin可以作为一个基础概念，可以再引入一个扩展类来包含多个plugins？

**Comment by Saul-Mirone** [comment]
> > 那可能一个feature需要的plugin很多，例如table这个feature，你会需要很多plugin，这样会不会太琐碎了。
> 
> plugin可以作为一个基础概念，可以再引入一个扩展类来包含多个plugins？

我可以试着实现一版本，我先合并这个pr，然后提一个新的

**Pull request merged**
