### PR TITLE
Make emotion can be configured

### PR DESCRIPTION
**Pull request by Saul-Mirone**
✅ Closes: [233](https://github.com/Saul-Mirone/milkdown/issues/233)

```typescript
import { emotionConfigCtx } from '@milkdown/core';

const editor = Editor.make()
    .config((ctx) => {
        ctx.set(emotionConfigCtx, {
            key: 'milkdown-instance',
            container: document.querySelector('#app') as HTMLElement,
        });
    })
// ....
```

### CODE REVIEW

**Comment by echarles** [comment]
Is there an example of such a configuration? That would help to get started with that new great feature. Thx.

**Comment by Saul-Mirone** [comment]
> Is there an example of such a configuration? That would help to get started with that new great feature. Thx.

The example is already in PR description, isn't it?

**Comment by echarles** [comment]
True, but I was thinking more on a real example with code and deployed application to show in real what kind of configuration can be applied to emotion. Eg. It is not clear to me if we can theme the ui with that config, or just override some emotion settings, and what for.

**Comment by Saul-Mirone** [comment]
> True, but I was thinking more on a real example with code and deployed application to show in real what kind of configuration can be applied to emotion. Eg. It is not clear to me if we can theme the ui with that config, or just override some emotion settings, and what for.

It's just used for providing custom instance of emotion:

https://emotion.sh/docs/@emotion/css#custom-instances

**Pull request merged**
