### PR TITLE
feat: 🎸 provide mermaid theme options for diagram

### PR DESCRIPTION
**Pull request by quank123wip**
Note that this commit includes various fixes needed to be reviewed includes eslint-disable files. Please remind.

Edit: I will remove the type definition after merged mermaid type definition, and add themeVariable configuration after I finished that part of type definition.

### CODE REVIEW

**Comment by Saul-Mirone** [comment]
Could you also upgrade readme? And seems that there are conflicts in this branch.

**Comment by quank123wip** [comment]
> Could you please also upgrade readme? And seems that there are conflicts in this branch.

I'm sorry for bothering you once again, but can you give me a brief description of the conflicts, or you can simply post a diff about the conflicts, I'm currently working on a low end device and can't use specific tools for this.

**Comment by Saul-Mirone** [comment]
I don't have a clearly idea. I just know it from here:
image
Maybe you can sync with remote and try rebase your changes?

**Comment by Saul-Mirone** [comment]
Seems it's
image
and
image

**Comment by quank123wip** [comment]
I rebased my changes with latest origin. But I need a little help on README. I don't really understand how the plugins are configured by args, and I haven't read the part of plugin definitions like AtomList.create(). Should I use diagram() or diagram.configure()? Please mention me if you see this.

**Comment by Saul-Mirone** [comment]
```typescript
import { Editor } from '@milkdown/core';
import { commonmark } from '@milkdown/preset-commonmark';
import { nord } from '@milkdown/theme-nord';

import { diagram, diagramNode } from '@milkdown/plugin-diagram';

Editor.make().use(nord).use(commonmark).use(diagram.configure(diagramNode, {
  // options
})).create();
```
Seems we also need to export diagramNode if we want to make it can be configured.

**Comment by quank123wip** [comment]
> ```ts
> import { Editor } from '@milkdown/core';
> import { commonmark } from '@milkdown/preset-commonmark';
> import { nord } from '@milkdown/theme-nord';
> 
> import { diagram, diagramNode } from '@milkdown/plugin-diagram';
> 
> Editor.make().use(nord).use(commonmark).use(diagram.configure(diagramNode, {
>   // options
> })).create();
> ```
> 
> Seems we also need to export diagramNode if we want to make it can be configured.

That seems worked well. But it's painful for user to do it for such a simple problem, I will read more code and make another PR to simplify this. For now, I can make this workaround a temporary solution into the README, that could make v6 release earlier. What do you think? Should we perfect this or just release it with the workaround?

**Comment by Saul-Mirone** [comment]
> > ```ts
> > import { Editor } from '@milkdown/core';
> > import { commonmark } from '@milkdown/preset-commonmark';
> > import { nord } from '@milkdown/theme-nord';
> > 
> > import { diagram, diagramNode } from '@milkdown/plugin-diagram';
> > 
> > Editor.make().use(nord).use(commonmark).use(diagram.configure(diagramNode, {
> >   // options
> > })).create();
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Seems we also need to export diagramNode if we want to make it can be configured.
> 
> That seems worked well. But it's painful for user to do it for such a simple problem, I will read more code and make another PR to simplify this. For now, I can make this workaround a temporary solution into the README, that could make v6 release earlier. What do you think? Should we perfect this or just release it with the workaround?
> 
> EDIT: Release unstable API is maybe not good for the project's continous and useability. I would like to do this before it release.

In fact. We can rename the `diagramNode` to `diagram` so user can use it like `editor.use(diagram())` and `editor.use(diagram(options))`. Here I create it using `AtomList` is due to some legacy issues.

**Comment by Saul-Mirone** [comment]
Also. From your commit history I notice that you're likely to use `merge` more often than `rebase`. Personally I prefer to use `rebase` because it can get you rid of some annoying conflicts. Here's an article that helps me to understand their difference:
https://medium.com/singlestone/a-git-workflow-using-rebase-1b1210de83e5

**Comment by quank123wip** [comment]
> Also. From your commit history I notice that you're likely to use `merge` more often than `rebase`. Personally I prefer to use `rebase` because it can get you rid of some annoying conflicts. Here's an article that helps me to understand their difference: https://medium.com/singlestone/a-git-workflow-using-rebase-1b1210de83e5 If you know their differences and still prefer `merge`. Then just ignore me.

Sorry for that. I'm not a skilled git user and just learnt how to use the very basic base control feature. In fact I currently don't understand these differences at all. I have few online co-op experiences though. Due to the importance of a well organized version control system, I will put my effort in learning basic git knowledges. Hope I wouldn't bother you for such a simple issue again. And again, sincerely, I'm sorry. ♥

**Comment by Saul-Mirone** [comment]
> > Also. From your commit history I notice that you're likely to use `merge` more often than `rebase`. Personally I prefer to use `rebase` because it can get you rid of some annoying conflicts. Here's an article that helps me to understand their difference: https://medium.com/singlestone/a-git-workflow-using-rebase-1b1210de83e5 If you know their differences and still prefer `merge`. Then just ignore me.
> 
> 
> 
> Sorry for that. I'm not a skilled git user and just learnt how to use the very basic base control feature. In fact I currently don't understand these differences at all. I have few online co-op experiences though. Due to the importance of a well organized version control system, I will put my effort in learning basic git knowledges. Hope I wouldn't bother you for such a simple issue again. And again, sincerely, I'm sorry. ♥

No worry. You don't need to apologize for this. Everyone starts from this.

**Comment by quank123wip** [comment]
Done. Please mark this as a breaking change if you merge.

**Comment by Saul-Mirone** [comment]
> Done. Please mark this as a breaking change if you merge.

Seems there's some errors in common

**Comment by quank123wip** [comment]
Using git merge really produced a lot of waste commits. I'm stepping on learning git rebase, hope I can reduce them later.

**Pull request merged**
