### PR TITLE
add angular support

### PR DESCRIPTION
**Pull request by Muromi-Rikka**

### CODE REVIEW

**Comment by Muromi-Rikka** [comment]
#103

**Comment by Saul-Mirone** [comment]
Thanks for your contribution.

I've reviewed this PR since yesterday. However, ignoring the detail problems in the implementation. I think it's better to not include this package in this repo. Because I don't familiar with angular and I can't make sure this package will be well maintained.

I suggest that  you can maintain the angular support as an community support in your own repo. And I can include your package in the document and contribute to your project.

**Comment by Muromi-Rikka** [comment]
> 感谢您的贡献。
> 
> 从昨天开始我已经审查了这个 PR。但是，忽略了实现中的细节问题。我认为最好不要在这个 repo 中包含这个包。因为我不熟悉 Angular，我不能确保这个包会得到很好的维护。
> 
> 我建议您可以在自己的存储库中保持角度支持作为社区支持。我可以将您的包包含在文档中并为您的项目做出贡献。

thank

**Comment by Muromi-Rikka** [comment]
thanks

**Pull request closed without merging**
