### PR TITLE
fix: refractor (dep -> peerDep)

### PR DESCRIPTION
**Pull request by shiyiya**
`refractor/lib/all` is not necessary，should not be packed together. So that we can control it from the outside.

### CODE REVIEW

**Comment by shiyiya** [comment]
`Refractor ` doesn't seem to support custom languages?

**Comment by Saul-Mirone** [comment]
refractor doesn't support custom languages. So I think we may don't need others to control it...

**Comment by shiyiya** [comment]
I try :
image
But this needs to be changed on the refractor side

**Comment by shiyiya** [comment]
But I think it's necessary, don't you think?

**Comment by Saul-Mirone** [comment]
You changes seems cannot be compiled correctly. You need to make sure it can pass the ci validation.

**Comment by Saul-Mirone** [comment]
Also, I think we can consider to make it can be configured in `Editor.config` instead of make it as peer dependency. Like what I did with plugin-listener.

**Comment by shiyiya** [comment]
如果配置能将不需要的依赖（lang）排除那最好不过。
If the configuration can exclude unnecessary dependencies, it's best.

**Comment by Saul-Mirone** [comment]
But refractor seems doesn't have this feature.

**Comment by shiyiya** [comment]
image

prism plugn(refractor/lib/all) is bigger than milkdown

**Comment by Saul-Mirone** [comment]
> image
> 
> prism plugn(refractor/lib/all) is bigger than milkdown
Screen Shot 2022-01-28 at 6 56 33 PM
This can be easily solved by make it as external for bundle.

**Comment by shiyiya** [comment]
?
image

**Comment by shiyiya** [comment]
maybe external does not seem to be a good solution

**Comment by shiyiya** [comment]
It is better for the refractor to support this feature . 😆

**Comment by Saul-Mirone** [comment]
> It is better for the refractor to support this feature . 😆

yeah, that's the best🤠

**Pull request closed without merging**
