### PR TITLE
fix: 🐛 Undo Redo broken with CapsLock

### PR DESCRIPTION
**Pull request by z-950**
## Summary
[Undo Redo broken with Caps Lock](https://discuss.prosemirror.net/t/undo-redo-broken-with-caps-lock-on-website-demo/4068)

## How did you test this change?
By manually.

### CODE REVIEW

**Comment by Saul-Mirone** [comment]
This breaks the behavior of Mod-Shift-z to redo a change.

**Comment by z-950** [comment]
Fixed.

**Comment by Saul-Mirone** [comment]
Seems still not working on macOS.

**Comment by Saul-Mirone** [comment]
I think `Mod-Shift-z` may conflict with `Mod-Z`.

**Comment by z-950** [comment]
Yes, I think it's an issue of `prosemirror-keymap`.

**Pull request closed without merging**
